imu:
  body_q_imu: [0.5, -0.5, 0.5, -0.5] # [q]
  acc_noise_density: 1.8032560209070164e-02
  acc_random_walk: 4.9098209065407837e-04
  gyr_noise_density: 2.1483047214801627e-03
  gyr_random_walk: 1.5036495212638137e-05
  initializer_buffer_size: 100
  initializer_max_acc_std: 3.0

#pos_sensor:
#  quantity: 1
#  sensor1:
#    name: "mocap_position"
#    body_T_sensor:
#    local_T_global:
#    input_with_cov: 0
#    n_pos:

pose_sensor:
  quantity: 2
  sensor1:
    name: "orb_localization"
    body_T_sensor: [ -0.02168, -0.02052, 0.00512, 0.5, -0.5, 0.5, -0.5 ] # [p, q]
    input_with_cov: 0
    n_pos: 0.1
    n_q: 1
    use_for_initial: 0
    use_for_global: 0
  sensor2:
    name: "mocap"
    body_T_sensor: [ -0.0618112, -0.0178466, 0.105516, 0.0051576, -0.0028813, -0.0006538, 0.9999823 ]
    # local_T_global: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0 ]
    input_with_cov: 0
    n_pos: 0.01
    n_q: 0.1
    use_for_initial: 0
    use_for_global: 1

odom_sensor:
  quantity: 1
  sensor1:
    name: "t265"
    body_T_sensor: [ -0.17, 0.0, 0.0, -0.3826545, 0.0, 0.9238915, 0.0 ]
    input_with_cov: 1
    use_for_initial: 1
    use_for_global: 0
  #  sensor2:
  #    imu_T_sensor:  # [p, q(x, y, z, w)]
  #    world_T_map:  # [p, q] note: write it if you want to specify the T or just delete the node which mean use the first frame to calculate the T
  #    input_with_cov: 0
  #    n_pos:  # unit: m
  #    n_q:  # unit: degree
  #    n_v:  # unit: m/s
  #    use_for_initial: 0 # note: only one sensor can be used for initial
  #    use_for_global: 0 # note: only one sensor can be used for global

gps_sensor:
  quantity: 0
